### ISSUE TITLE
[BUG] Image Store Issue

### ISSUE THREAD

**Issue by akinsey** [epochtalk/epochtalk#315]
When on local storage for images and posting a local image the server errors

`[img]/static/images/avatar.png[/img]`

```
message: Uncaught error: Invalid URI "/static/img/avatar.png" stack: Error: Uncaught error: Invalid URI "/static/img/avatar.png"
    at Request.init (/home/akinsey/Development/epochtalk/node_modules/request/request.js:276:31)
    at new Request (/home/akinsey/Development/epochtalk/node_modules/request/request.js:130:8)
    at request (/home/akinsey/Development/epochtalk/node_modules/request/index.js:54:10)
    at Object.local.uploadImage (/home/akinsey/Development/epochtalk/server/plugins/imageStore/local.js:83:21)
    at Object.local.saveImage (/home/akinsey/Development/epochtalk/server/plugins/imageStore/local.js:59:11)
    at Object.images.saveImage (/home/akinsey/Development/epochtalk/server/plugins/imageStore/common.js:41:47)
    at Promise.map (/home/akinsey/Development/epochtalk/server/plugins/imageStore/common.js:106:27)
    at bound (domain.js:280:14)
    at runBound (domain.js:293:12)
    at tryCatcher (/home/akinsey/Development/epochtalk/node_modules/bluebird/js/release/util.js:16:23)
    at MappingPromiseArray._promiseFulfilled (/home/akinsey/Development/epochtalk/node_modules/bluebird/js/release/map.js:61:38)
    at MappingPromiseArray.PromiseArray._iterate (/home/akinsey/Development/epochtalk/node_modules/bluebird/js/release/promise_array.js:114:31)
    at MappingPromiseArray.init (/home/akinsey/Development/epochtalk/node_modules/bluebird/js/release/promise_array.js:78:10)
    at MappingPromiseArray._asyncInit (/home/akinsey/Development/epochtalk/node_modules/bluebird/js/release/map.js:30:10)
    at Async._drainQueue (/home/akinsey/Development/epochtalk/node_modules/bluebird/js/release/async.js:138:12)
    at Async._drainQueues (/home/akinsey/Development/epochtalk/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/home/akinsey/Development/epochtalk/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
Debug: internal, implementation, error 
    Error: Uncaught error: Invalid URI "/static/img/avatar.png"
    at Request.init (/home/akinsey/Development/epochtalk/node_modules/request/request.js:276:31)
    at new Request (/home/akinsey/Development/epochtalk/node_modules/request/request.js:130:8)
    at request (/home/akinsey/Development/epochtalk/node_modules/request/index.js:54:10)
    at Object.local.uploadImage (/home/akinsey/Development/epochtalk/server/plugins/imageStore/local.js:83:21)
    at Object.local.saveImage (/home/akinsey/Development/epochtalk/server/plugins/imageStore/local.js:59:11)
    at Object.images.saveImage (/home/akinsey/Development/epochtalk/server/plugins/imageStore/common.js:41:47)
    at Promise.map (/home/akinsey/Development/epochtalk/server/plugins/imageStore/common.js:106:27)
    at bound (domain.js:280:14)
    at runBound (domain.js:293:12)
    at tryCatcher (/home/akinsey/Development/epochtalk/node_modules/bluebird/js/release/util.js:16:23)
    at MappingPromiseArray._promiseFulfilled (/home/akinsey/Development/epochtalk/node_modules/bluebird/js/release/map.js:61:38)
    at MappingPromiseArray.PromiseArray._iterate (/home/akinsey/Development/epochtalk/node_modules/bluebird/js/release/promise_array.js:114:31)
    at MappingPromiseArray.init (/home/akinsey/Development/epochtalk/node_modules/bluebird/js/release/promise_array.js:78:10)
    at MappingPromiseArray._asyncInit (/home/akinsey/Development/epochtalk/node_modules/bluebird/js/release/map.js:30:10)
    at Async._drainQueue (/home/akinsey/Development/epochtalk/node_modules/bluebird/js/release/async.js:138:12)
    at Async._drainQueues (/home/akinsey/Development/epochtalk/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/home/akinsey/Development/epochtalk/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
```

**Comment by akinsey** [comment]
Fixed in bd2198098b863661b692b570f36813abaaef899a
