### ISSUE TITLE
[BUG] Board with same name

### ISSUE THREAD

**Issue by luluwebmaster** [epochtalk/epochtalk#497]
When I try to save two board with the same name : 

![c5547c76](https://user-images.githubusercontent.com/15527061/53537945-0cafb980-3b0c-11e9-8f14-3fdd2f6ca7f1.png)

In the console :

`[error] message: Uncaught error: slug.replace is not a function, stack: TypeError: Uncaught error: slug.replace is not a function`

**Comment by akinsey** [comment]
Thank you for the bug reports, we will be working on these!

**Comment by luluwebmaster** [comment]
Hello,

After a `git pull`, the bug is already here : 

![image](https://user-images.githubusercontent.com/15527061/56443475-217f2100-62f5-11e9-9889-f4b07eda49b5.png)

When I save, I have this error on console : 

```
190419/204748.832, [error] message: Uncaught error: slug.replace is not a function, stack: TypeError: Uncaught error: slug.replace is not a function
    at exports.decode (/var/nodejs/cryptos-currencies.com/epochtalk/node_modules/slugid/slugid.js:44:20)
    at /var/nodejs/cryptos-currencies.com/epochtalk/node_modules/epochtalk-core-pg/helper.js:93:22
    at Array.map (<anonymous>)
    at /var/nodejs/cryptos-currencies.com/epochtalk/node_modules/epochtalk-core-pg/helper.js:87:19
    at Array.map (<anonymous>)
    at slugTransform (/var/nodejs/cryptos-currencies.com/epochtalk/node_modules/epochtalk-core-pg/helper.js:85:10)
    at Object.deslugify (/var/nodejs/cryptos-currencies.com/epochtalk/node_modules/epochtalk-core-pg/helper.js:51:12)
    at Object.module.exports [as updateCategories] (/var/nodejs/cryptos-currencies.com/epochtalk/modules/ept-boards/db/updateCategories.js:9:25)
    at handler (/var/nodejs/cryptos-currencies.com/epochtalk/server/routes/admin/boards/config.js:146:37)
    at Object.internals.handler (/var/nodejs/cryptos-currencies.com/epochtalk/node_modules/hapi/lib/handler.js:101:51)
    at request._protect.run (/var/nodejs/cryptos-currencies.com/epochtalk/node_modules/hapi/lib/handler.js:32:23)
    at module.exports.internals.Protect.internals.Protect.run (/var/nodejs/cryptos-currencies.com/epochtalk/node_modules/hapi/lib/protect.js:60:12)
    at exports.execute (/var/nodejs/cryptos-currencies.com/epochtalk/node_modules/hapi/lib/handler.js:26:22)
    at each (/var/nodejs/cryptos-currencies.com/epochtalk/node_modules/hapi/lib/request.js:401:16)
    at iterate (/var/nodejs/cryptos-currencies.com/epochtalk/node_modules/items/lib/index.js:36:13)
    at done (/var/nodejs/cryptos-currencies.com/epochtalk/node_modules/items/lib/index.js:28:25)
Debug: internal, implementation, error
    TypeError: Uncaught error: slug.replace is not a function
    at exports.decode (/var/nodejs/cryptos-currencies.com/epochtalk/node_modules/slugid/slugid.js:44:20)
    at /var/nodejs/cryptos-currencies.com/epochtalk/node_modules/epochtalk-core-pg/helper.js:93:22
    at Array.map (<anonymous>)
    at /var/nodejs/cryptos-currencies.com/epochtalk/node_modules/epochtalk-core-pg/helper.js:87:19
    at Array.map (<anonymous>)
    at slugTransform (/var/nodejs/cryptos-currencies.com/epochtalk/node_modules/epochtalk-core-pg/helper.js:85:10)
    at Object.deslugify (/var/nodejs/cryptos-currencies.com/epochtalk/node_modules/epochtalk-core-pg/helper.js:51:12)
    at Object.module.exports [as updateCategories] (/var/nodejs/cryptos-currencies.com/epochtalk/modules/ept-boards/db/updateCategories.js:9:25)
    at handler (/var/nodejs/cryptos-currencies.com/epochtalk/server/routes/admin/boards/config.js:146:37)
    at Object.internals.handler (/var/nodejs/cryptos-currencies.com/epochtalk/node_modules/hapi/lib/handler.js:101:51)
    at request._protect.run (/var/nodejs/cryptos-currencies.com/epochtalk/node_modules/hapi/lib/handler.js:32:23)
    at module.exports.internals.Protect.internals.Protect.run (/var/nodejs/cryptos-currencies.com/epochtalk/node_modules/hapi/lib/protect.js:60:12)
    at exports.execute (/var/nodejs/cryptos-currencies.com/epochtalk/node_modules/hapi/lib/handler.js:26:22)
    at each (/var/nodejs/cryptos-currencies.com/epochtalk/node_modules/hapi/lib/request.js:401:16)
    at iterate (/var/nodejs/cryptos-currencies.com/epochtalk/node_modules/items/lib/index.js:36:13)
    at done (/var/nodejs/cryptos-currencies.com/epochtalk/node_modules/items/lib/index.js:28:25)
```

**Comment by luluwebmaster** [comment]
My bad, I don't have pull the good branch ^^

After `git pull origin fixes-2019` it's good 💯

**Comment by akinsey** [comment]
@luluwebmaster Awesome! just keep in mind the branch is still under active development, if you're going to use the latest from that branch you should make sure you pull the lastest from master in `epoch` and `core-pg`

Make sure you run the latest migration out of epoch.

To get the newest role/permissions changes which fix self moderation, you will have to delete your roles table, if you have any custom roles they will be unfortunately deleted... This is something we will be working on in the future, being able to refresh the roles from the base set of permissions without wiping the roles table.

To do this connect to your Postgres DB using psql
```
SET session_replication_role = 'replica';
DELETE from roles;
SET session_replication_role = 'origin';
```

This will allow you to delete the roles without removing all the users from those associated roles. The roles will be reinserted on restart of the epochtalk server and any users within those roles should still be there.

**Comment by luluwebmaster** [comment]
Hmm, where I can found / How I can update `core-pg` ?
