### ISSUE TITLE
[BUG] Error on deleting account.

### ISSUE THREAD

**Issue by luluwebmaster** [epochtalk/epochtalk#498]
On random accounts, when I try to delete account, I can't.

![image](https://user-images.githubusercontent.com/15527061/53539767-2c96ab80-3b13-11e9-8a58-1b55041c2b24.png)

Error on console : 

`[error] message: update or delete on table "users" violates foreign key constraint "preferences_user_id_fkey" on table "preferences", stack: error: update or delete on table "users" violates foreign key constraint "preferences_user_id_fkey" on table "preferences"`.

**Comment by akinsey** [comment]
This required a fix to the migrations in the `epoch` project.

To resolve this issue please pull the latest of the `epoch` project and run `mix ecto.migrate`

https://github.com/epochtalk/epoch/commit/54ba7252e495cb143fa373c9f0b7343ce0810666

**Comment by luluwebmaster** [comment]
Nice, it's good thank you 👍

**Comment by luluwebmaster** [comment]
Hmm,

I have another random account which is a problem when I try to delete :

```
190419/224254.973, [error] message: update or delete on table "users" violates foreign key constraint "notifications_sender_id_fkey" on table "notifications", stack: error: update or delete on table "users" violates foreign key constraint "notifications_sender_id_fkey" on table "notifications"
    at Connection.parseE (/var/nodejs/cryptos-currencies.com/epochtalk/node_modules/epochtalk-core-pg/node_modules/pg/lib/connection.js:555:11)
    at Connection.parseMessage (/var/nodejs/cryptos-currencies.com/epochtalk/node_modules/epochtalk-core-pg/node_modules/pg/lib/connection.js:380:19)
    at Socket.<anonymous> (/var/nodejs/cryptos-currencies.com/epochtalk/node_modules/epochtalk-core-pg/node_modules/pg/lib/connection.js:120:22)
    at Socket.emit (events.js:197:13)
    at Socket.EventEmitter.emit (domain.js:464:23)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:145:17)
From previous event:
    at processImmediate (timers.js:637:19)
    at process.topLevelDomainCallback (domain.js:126:23)
From previous event:
    at Object.module.exports [as delete] (/var/nodejs/cryptos-currencies.com/epochtalk/modules/ept-users/db/delete.js:12:10)
    at handler (/var/nodejs/cryptos-currencies.com/epochtalk/modules/ept-users/routes/delete.js:37:42)
    at internals.handler (/var/nodejs/cryptos-currencies.com/epochtalk/node_modules/hapi/lib/handler.js:101:51)
    at bound (domain.js:400:14)
    at runBound (domain.js:413:12)
    at Items.serial (/var/nodejs/cryptos-currencies.com/epochtalk/node_modules/hapi/lib/handler.js:68:16)
    at done (/var/nodejs/cryptos-currencies.com/epochtalk/node_modules/items/lib/index.js:31:25)
    at done (/var/nodejs/cryptos-currencies.com/epochtalk/node_modules/items/lib/index.js:63:25)
    at pre (/var/nodejs/cryptos-currencies.com/epochtalk/node_modules/hapi/lib/handler.js:54:24)
    at finalize (/var/nodejs/cryptos-currencies.com/epochtalk/node_modules/hapi/lib/handler.js:291:20)
    at wrapped (/var/nodejs/cryptos-currencies.com/epochtalk/node_modules/hapi/node_modules/hoek/lib/index.js:879:20)
    at module.exports.internals.Response.internals.Response._processPrepare (/var/nodejs/cryptos-currencies.com/epochtalk/node_modules/hapi/lib/response.js:548:16)
    at module.exports.internals.Response.internals.Response._prepare (/var/nodejs/cryptos-currencies.com/epochtalk/node_modules/hapi/lib/response.js:476:21)
    at process.nextTick (/var/nodejs/cryptos-currencies.com/epochtalk/node_modules/hapi/lib/reply.js:183:22)
    at processTicksAndRejections (internal/process/next_tick.js:74:9)
```

Account : https://www.cryptos-currencies.com/profiles/A_specter_is_haunting_the_modern_world_the_specter_of_crypto_anarchy.

**Comment by akinsey** [comment]
I will look into this can you please open a new issue 🙏

Thanks,
Anthony

**Comment by luluwebmaster** [comment]
Oh, yes sorry ^^
