### ISSUE TITLE
Metadata does not exist.

### ISSUE THREAD

**Issue by luluwebmaster** [epochtalk/epochtalk#524]
Hello,

After a `Epoch` update and migration, and `Epochtalk` update, I have this error when I try to show a subject : 

```
190419/210217.336, [error] message: column p.metadata does not exist, stack: PostgresError: column p.metadata does not exist
    at handlePgError (/var/nodejs/cryptos-currencies.com/epochtalk/node_modules/epochtalk-core-pg/errors.js:33:17)
    at bound (domain.js:400:14)
    at runBound (domain.js:413:12)
    at processImmediate (timers.js:637:19)
    at process.topLevelDomainCallback (domain.js:126:23)
From previous event:
    at Object.db.sqlQuery (/var/nodejs/cryptos-currencies.com/epochtalk/node_modules/epochtalk-core-pg/db.js:45:9)
    at Object.module.exports [as byThread] (/var/nodejs/cryptos-currencies.com/epochtalk/modules/ept-posts/db/byThread.js:32:13)
    at processing (/var/nodejs/cryptos-currencies.com/epochtalk/modules/ept-posts/routes/byThread.js:132:35)
    at /var/nodejs/cryptos-currencies.com/epochtalk/node_modules/hapi/lib/handler.js:301:20
    at Items.parallel (/var/nodejs/cryptos-currencies.com/epochtalk/node_modules/hapi/lib/handler.js:44:13)
    at Object.exports.parallel (/var/nodejs/cryptos-currencies.com/epochtalk/node_modules/items/lib/index.js:70:13)
    at each (/var/nodejs/cryptos-currencies.com/epochtalk/node_modules/hapi/lib/handler.js:42:15)
    at iterate (/var/nodejs/cryptos-currencies.com/epochtalk/node_modules/items/lib/index.js:36:13)
    at done (/var/nodejs/cryptos-currencies.com/epochtalk/node_modules/items/lib/index.js:28:25)
    at done (/var/nodejs/cryptos-currencies.com/epochtalk/node_modules/items/lib/index.js:63:25)
    at pre (/var/nodejs/cryptos-currencies.com/epochtalk/node_modules/hapi/lib/handler.js:54:24)
    at finalize (/var/nodejs/cryptos-currencies.com/epochtalk/node_modules/hapi/lib/handler.js:291:20)
    at wrapped (/var/nodejs/cryptos-currencies.com/epochtalk/node_modules/hapi/node_modules/hoek/lib/index.js:879:20)
    at module.exports.internals.Response.internals.Response._processPrepare (/var/nodejs/cryptos-currencies.com/epochtalk/node_modules/hapi/lib/response.js:548:16)
    at module.exports.internals.Response.internals.Response._prepare (/var/nodejs/cryptos-currencies.com/epochtalk/node_modules/hapi/lib/response.js:476:21)
    at process.nextTick (/var/nodejs/cryptos-currencies.com/epochtalk/node_modules/hapi/lib/reply.js:183:22)
    at processTicksAndRejections (internal/process/next_tick.js:74:9)
```

Is it a problem with my migration ?

**Comment by akinsey** [comment]
Hello! I just responded in the other thread!

@luluwebmaster <https://github.com/luluwebmaster> Awesome! just keep in mind the branch is still under active development, if you're going to use the latest from that branch you should make sure you pull the lastest from master in epoch and core-pg

Make sure you run the latest migration out of epoch.

To get the newest role/permissions changes which fix self moderation, you will have to delete your roles table, if you have any custom roles they will be unfortunately deleted... This is something we will be working on in the future, being able to refresh the roles from the base set of permissions without wiping the roles table.

To do this connect to your Postgres DB using psql

SET session_replication_role = 'replica';
DELETE from roles;
SET session_replication_role = 'origin';
This will allow you to delete the roles without removing all the users from those associated roles. The roles will be reinserted on restart of the epochtalk server and any users within those roles should still be there.

We will be merging these changes soon

**Comment by akinsey** [comment]
@luluwebmaster because this is still in dev and not pushed to npm you will have to manually link it in your package.json in the root of the project. Then re run yarn install.

in package.json change this line:
`"epochtalk-core-pg": "^1.0.9",`

to this:
`"epochtalk-core-pg": "https://github.com/epochtalk/core-pg.git",`

then run this in the root of the project:
`yarn install`

**Comment by luluwebmaster** [comment]
Okay,

After this update, and a new `git pull` in `Epoch`, the problem is now solved !

Thank you 👍
