### ISSUE TITLE
Cannot read property 'server' of undefined.

### ISSUE THREAD

**Issue by luluwebmaster** [epochtalk/epochtalk#525]
Hello,

New problem when I try to see profile of user : 

```
190419/220040.093, [error] message: Cannot read property 'server' of undefined, stack: TypeError: Cannot read property 'server' of undefined
    at Object.cleanPosts (/var/nodejs/cryptos-currencies.com/epochtalk/modules/ept-posts/common/index.js:150:36)
    at /var/nodejs/cryptos-currencies.com/epochtalk/modules/ept-posts/routes/pageByUser.js:95:21
    at bound (domain.js:400:14)
    at Promise.runBound (domain.js:413:12)
    at processImmediate (timers.js:637:19)
From previous event:
    at processing (/var/nodejs/cryptos-currencies.com/epochtalk/modules/ept-posts/routes/pageByUser.js:90:25)
    at /var/nodejs/cryptos-currencies.com/epochtalk/node_modules/hapi/lib/handler.js:301:20
    at Items.parallel (/var/nodejs/cryptos-currencies.com/epochtalk/node_modules/hapi/lib/handler.js:44:13)
    at Object.exports.parallel (/var/nodejs/cryptos-currencies.com/epochtalk/node_modules/items/lib/index.js:70:13)
    at each (/var/nodejs/cryptos-currencies.com/epochtalk/node_modules/hapi/lib/handler.js:42:15)
    at iterate (/var/nodejs/cryptos-currencies.com/epochtalk/node_modules/items/lib/index.js:36:13)
    at done (/var/nodejs/cryptos-currencies.com/epochtalk/node_modules/items/lib/index.js:28:25)
    at done (/var/nodejs/cryptos-currencies.com/epochtalk/node_modules/items/lib/index.js:63:25)
    at pre (/var/nodejs/cryptos-currencies.com/epochtalk/node_modules/hapi/lib/handler.js:54:24)
    at finalize (/var/nodejs/cryptos-currencies.com/epochtalk/node_modules/hapi/lib/handler.js:291:20)
    at wrapped (/var/nodejs/cryptos-currencies.com/epochtalk/node_modules/hapi/node_modules/hoek/lib/index.js:879:20)
    at module.exports.internals.Response.internals.Response._processPrepare (/var/nodejs/cryptos-currencies.com/epochtalk/node_modules/hapi/lib/response.js:548:16)
    at module.exports.internals.Response.internals.Response._prepare (/var/nodejs/cryptos-currencies.com/epochtalk/node_modules/hapi/lib/response.js:476:21)
    at process.nextTick (/var/nodejs/cryptos-currencies.com/epochtalk/node_modules/hapi/lib/reply.js:183:22)
    at processTicksAndRejections (internal/process/next_tick.js:74:9)
    at runNextTicks (internal/process/next_tick.js:51:3)
    at processImmediate (timers.js:610:7)
    at process.topLevelDomainCallback (domain.js:126:23)
```

**Comment by akinsey** [comment]
Pull from fixes-2019 of Epochtalk again. I fixed this within the past hour. 

Thanks,
Anthony

**Comment by luluwebmaster** [comment]
Oh, yes, it's good thank you !
