### ISSUE TITLE
[BUG] Test forum : Default users can't see posts.

### ISSUE THREAD

**Issue by luluwebmaster** [epochtalk/epochtalk#574]
Hello,

When a basic user try to see a post, this error has returned : 

![image](https://user-images.githubusercontent.com/15527061/59944340-ce485c80-9464-11e9-8506-3e043550d043.png)

But when I try to see the post without account or with my admin account, I don't have this error.

Full error from server console : 

```
190621/184118.624, [response] http://localhost:8080: post /api/threads/U2cRKzLrTyCHKcVaCIgeAw/viewed {} 200 (70ms)
190621/184118.690, [error] message: method is not a function, stack: TypeError: method is not a function
    at Object.isMod (/var/nodejs/cryptos-currencies.com/epochtalk/server/plugins/authorization/index.js:43:12)
    at Object.build (/var/nodejs/cryptos-currencies.com/epochtalk/server/plugins/authorization/index.js:138:34)
    at /var/nodejs/cryptos-currencies.com/epochtalk/modules/ept-posts/authorization/byThread.js:38:42
    at bound (domain.js:425:14)
    at runBound (domain.js:438:12)
    at processImmediate (internal/timers.js:443:21)
    at process.topLevelDomainCallback (domain.js:136:23)
From previous event:
    at postsByThread (/var/nodejs/cryptos-currencies.com/epochtalk/modules/ept-posts/authorization/byThread.js:33:4)
    at normalized (/var/nodejs/cryptos-currencies.com/epochtalk/node_modules/hapi/lib/methods.js:79:33)
    at result.method (/var/nodejs/cryptos-currencies.com/epochtalk/node_modules/hapi/lib/handler.js:246:16)
    at /var/nodejs/cryptos-currencies.com/epochtalk/node_modules/hapi/lib/handler.js:301:20
    at Items.parallel (/var/nodejs/cryptos-currencies.com/epochtalk/node_modules/hapi/lib/handler.js:44:13)
    at Object.exports.parallel (/var/nodejs/cryptos-currencies.com/epochtalk/node_modules/items/lib/index.js:70:13)
    at each (/var/nodejs/cryptos-currencies.com/epochtalk/node_modules/hapi/lib/handler.js:42:15)
    at iterate (/var/nodejs/cryptos-currencies.com/epochtalk/node_modules/items/lib/index.js:36:13)
    at Object.exports.serial (/var/nodejs/cryptos-currencies.com/epochtalk/node_modules/items/lib/index.js:39:9)
    at Object.internals.prerequisites (/var/nodejs/cryptos-currencies.com/epochtalk/node_modules/hapi/lib/handler.js:61:11)
    at request._protect.run (/var/nodejs/cryptos-currencies.com/epochtalk/node_modules/hapi/lib/handler.js:29:23)
    at module.exports.internals.Protect.internals.Protect.run (/var/nodejs/cryptos-currencies.com/epochtalk/node_modules/hapi/lib/protect.js:60:12)
    at exports.execute (/var/nodejs/cryptos-currencies.com/epochtalk/node_modules/hapi/lib/handler.js:26:22)
    at each (/var/nodejs/cryptos-currencies.com/epochtalk/node_modules/hapi/lib/request.js:401:16)
    at iterate (/var/nodejs/cryptos-currencies.com/epochtalk/node_modules/items/lib/index.js:36:13)
    at done (/var/nodejs/cryptos-currencies.com/epochtalk/node_modules/items/lib/index.js:28:25)
    at postValidate (/var/nodejs/cryptos-currencies.com/epochtalk/node_modules/hapi/lib/validation.js:70:20)
    at internals.Object._validateWithOptions (/var/nodejs/cryptos-currencies.com/epochtalk/node_modules/joi/lib/types/any/index.js:767:20)
    at module.exports.internals.Any.root.validate (/var/nodejs/cryptos-currencies.com/epochtalk/node_modules/joi/lib/index.js:147:23)
190621/184118.690, [response] http://localhost:8080: get /api/posts {"limit":25,"thread_id":"U2cRKzLrTyCHKcVaCIgeAw"} 500 (20ms)
```

Original bug post : https://bitcointalk.org/index.php?topic=5115500.msg51488234#msg51488234

**Comment by akinsey** [comment]
We have been working on a huge restructuring of epochtalk's code and this is one of the issues that has been fixed, I will be getting back to you soon with instructions on how to update your installation.

Thanks for your patience 🙏

**Comment by akinsey** [comment]
Please try the latest code and let me know if you're still having this issues 🙏

**Comment by luluwebmaster** [comment]
Hello,

Yes sorry for the response time, what I need to update ? Just Epochtalk ( With Git command ? ) ?

Thank you !

**Comment by akinsey** [comment]
Thank you!
