### ISSUE TITLE
Cannot see private message page.

### ISSUE THREAD

**Issue by luluwebmaster** [epochtalk/epochtalk#600]
> This should be fixed now!
> 
> You will need to pull the `epoch` project and run `mix ecto.migrate`
> 
> Then you need to pull the `epochtalk` project as well. You can now switch back to `master` branch if you aren't on it currently.

_Originally posted by @akinsey in https://github.com/epochtalk/epochtalk/issues/571#issuecomment-509453255_

Hello,

After theses pull, I cannot see private message page.

Console error : 

```
190711/141644.936, [error] message: Cannot read property 'subject' of null, stack: TypeError: Cannot read property 'subject' of null
    at /var/nodejs/cryptos-currencies.com/epochtalk/modules/ept-messages/db/messages/latest.js:55:39
    at bound (domain.js:425:14)
    at runBound (domain.js:438:12)
    at processImmediate (internal/timers.js:443:21)
    at process.topLevelDomainCallback (domain.js:136:23)
From previous event:
    at /var/nodejs/cryptos-currencies.com/epochtalk/modules/ept-messages/db/messages/latest.js:54:8
    at bound (domain.js:425:14)
    at runBound (domain.js:438:12)
    at bound (domain.js:425:14)
    at MappingPromiseArray.runBound (domain.js:438:12)
From previous event:
    at Object.module.exports [as latest] (/var/nodejs/cryptos-currencies.com/epochtalk/modules/ept-messages/db/messages/latest.js:50:4)
    at handler (/var/nodejs/cryptos-currencies.com/epochtalk/modules/ept-messages/routes/latest.js:47:43)
    at internals.handler (/var/nodejs/cryptos-currencies.com/epochtalk/node_modules/hapi/lib/handler.js:101:51)
    at bound (domain.js:425:14)
    at runBound (domain.js:438:12)
    at Items.serial (/var/nodejs/cryptos-currencies.com/epochtalk/node_modules/hapi/lib/handler.js:68:16)
    at done (/var/nodejs/cryptos-currencies.com/epochtalk/node_modules/items/lib/index.js:31:25)
    at done (/var/nodejs/cryptos-currencies.com/epochtalk/node_modules/items/lib/index.js:63:25)
    at pre (/var/nodejs/cryptos-currencies.com/epochtalk/node_modules/hapi/lib/handler.js:54:24)
    at finalize (/var/nodejs/cryptos-currencies.com/epochtalk/node_modules/hapi/lib/handler.js:291:20)
    at wrapped (/var/nodejs/cryptos-currencies.com/epochtalk/node_modules/hapi/node_modules/hoek/lib/index.js:879:20)
    at module.exports.internals.Response.internals.Response._processPrepare (/var/nodejs/cryptos-currencies.com/epochtalk/node_modules/hapi/lib/response.js:548:16)
    at module.exports.internals.Response.internals.Response._prepare (/var/nodejs/cryptos-currencies.com/epochtalk/node_modules/hapi/lib/response.js:476:21)
    at process.nextTick (/var/nodejs/cryptos-currencies.com/epochtalk/node_modules/hapi/lib/reply.js:183:22)
    at processTicksAndRejections (internal/process/task_queues.js:79:9)
```

**Comment by akinsey** [comment]
Hello @luluwebmaster, I invited you to the epochtalk slack if you'd like to join! We can help you resolve issues quicker there if youre interested!

Unfortunately this update wipes the messages table, this was a result of moving the table into a new schema with a different table structure for storing message content.

To fix the issue you are having you can just connect to the database and run the following commands, after that everything should start working again.

```
DELETE FROM messages.private_messages;
DELETE FROM messages.private_conversations;
```

Sorry for the inconvenience!

**Comment by luluwebmaster** [comment]
It's now good, thank you !
