### ISSUE TITLE
Cant delete thread with poll

### ISSUE THREAD

**Issue by akinsey** [epochtalk/epochtalk#625]
```
[error] message: update or delete on table "threads" violates foreign key constraint "polls_thread_id_fkey" on table "polls", stack: error: update or delete on table "threads" violates foreign key constraint "polls_thread_id_fkey" on table "polls"
    at Connection.parseE (/home/akinsey/Development/epochtalk/node_modules/pg/lib/connection.js:602:11)
    at Connection.parseMessage (/home/akinsey/Development/epochtalk/node_modules/pg/lib/connection.js:399:19)
    at Socket.<anonymous> (/home/akinsey/Development/epochtalk/node_modules/pg/lib/connection.js:121:22)
    at Socket.emit (events.js:198:13)
    at Socket.EventEmitter.emit (domain.js:448:20)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
From previous event:
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
    at process.topLevelDomainCallback (domain.js:126:23)
From previous event:
    at Object.module.exports [as purge] (/home/akinsey/Development/epochtalk/modules/ept-threads/db/purge.js:20:10)
    at handler (/home/akinsey/Development/epochtalk/modules/ept-threads/routes/purge.js:39:38)
    at module.exports.internals.Manager.execute (/home/akinsey/Development/epochtalk/node_modules/@hapi/hapi/lib/toolkit.js:41:33)
    at Object.internals.handler (/home/akinsey/Development/epochtalk/node_modules/@hapi/hapi/lib/handler.js:46:48)
    at exports.execute (/home/akinsey/Development/epochtalk/node_modules/@hapi/hapi/lib/handler.js:31:36)
190806/011152.605, (1565053912605:kkid-ubuntu:17242:jyz4llcw:10044) [response] http://localhost:8080: delete /api/threads/df5TZSYLR-yzbV5YTz4bHA {} 500 (37ms)
```

**Comment by akinsey** [comment]
Fixed in epoch project
https://github.com/epochtalk/epoch/commit/b592f1d79d0d4201833657e0d044639932aea7b0
