### ISSUE TITLE
Unable to create the first user.

### ISSUE THREAD

**Issue by mzch** [epochtalk/epochtalk#739]
Hi,

I setup epochtalk and tried to create the first user, then `node cli` print an error as below:
```
epoch@n18:~/epochtalk$ node cli create-user --admin mzch mzch@mzch.org
Creating user and emailing password reset link to: mzch@mzch.org
Error creating user: error: column "ignored_boards" of relation "preferences" does not exist
    at Connection.parseE (/srv/epoch/epochtalk/node_modules/pg/lib/connection.js:606:11)
    at Connection.parseMessage (/srv/epoch/epochtalk/node_modules/pg/lib/connection.js:403:19)
    at Socket.<anonymous> (/srv/epoch/epochtalk/node_modules/pg/lib/connection.js:123:22)
    at Socket.emit (events.js:210:5)
    at Socket.EventEmitter.emit (domain.js:475:20)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:182:23) {
  name: 'error',
  length: 138,
  severity: 'ERROR',
  code: '42703',
  detail: undefined,
  hint: undefined,
  position: '97',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_target.c',
  line: '1033',
  routine: 'checkInsertTargets'
}
```
Anyone can help me?

**Comment by akinsey** [comment]
Do you have the latest migration from the `epoch` project? It was merged in recently:
https://github.com/epochtalk/epoch/commits/master

If not please rerun the migration and let me know if you still have this issue!
@mzch

**Comment by unenglishable** [comment]
This is outlined in [step #4 of the README](https://github.com/epochtalk/epochtalk#4-checkout-and-run-migrations) 👍

**Comment by mzch** [comment]
Oh, I missed it, Thanks @unenglishable  !
But when I did `mix deps.get`, got an error as below:
```
Could not find Hex, which is needed to build dependency :dialyxir
Shall I install Hex? (if running non-interactively, use "mix local.hex --force") [Yn]
** (UndefinedFunctionError) function :inets.stop/2 is undefined (module :inets is not available)
    :inets.stop(:httpc, :mix)
    (mix) lib/mix/utils.ex:560: Mix.Utils.read_httpc/1
    (mix) lib/mix/utils.ex:501: Mix.Utils.read_path/2
    (mix) lib/mix/local.ex:149: Mix.Local.read_path!/2
    (mix) lib/mix/local.ex:126: Mix.Local.find_matching_versions_from_signed_csv!/2
    (mix) lib/mix/tasks/local.hex.ex:56: Mix.Tasks.Local.Hex.run_install/1
    (mix) lib/mix/dep/loader.ex:168: Mix.Dep.Loader.with_scm_and_app/4
    (mix) lib/mix/dep/loader.ex:121: Mix.Dep.Loader.to_dep/3
```
Could you tell me how to fix this issue?

**Comment by mzch** [comment]
Hi @unenglishable ,
I tried to create user by using cli tool. First as your mentions in README, I tried `node cli --create` but it failed. Then I tried `node cli createuser user mail@example.com`, but no mail has arrived. Finally, I tried `cli/create_admin.js` and got successful, is it OK?

**Comment by TheMoFo** [comment]
they moved from npm to yarn #672 
try "yarn cli --create"
also "yarn run serve" to open sv
gl

**Comment by mzch** [comment]
@TheMoFo Thanks!
