### ISSUE TITLE
When trying to launch serve errer appears

### ISSUE THREAD

**Issue by timohzbs** [epochtalk/epochtalk#844]
Hello,

I setup everything like in your instructions.
When I run `npm run serve` it gets me this error:

```
root@vm:/etc/epochtalk# npm run serve

> epochtalk@0.4.18 serve /etc/epochtalk
> node ./scripts/serve.js

Cleaning Complete.
Loading Bar CSS Copied.
SASS Compilation Complete
fs.js:646
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'server.key'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at Object.<anonymous> (/etc/epochtalk/websocket-server/config.js:32:13)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/etc/epochtalk/websocket-server/index.js:6:14)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
Webpack Complete.
fs.js:646
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
Error: ENOENT: no such file or directory, open 'server.key'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at Object.<anonymous> (/etc/epochtalk/websocket-server/config.js:32:13)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/etc/epochtalk/websocket-server/index.js:6:14)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)`


```

Could you tell my what issue this is?

**Comment by Rizzrack09** [comment]
you should try `yarn run serve`

**Comment by timohzbs** [comment]
> you should try `yarn run serve`

If running `yarn run serve` I get:

```
root@vm:/etc/epochtalk$ sudo yarn run serve
[sudo] password for timo: 
yarn run v1.22.4
$ node ./scripts/serve.js
Cleaning Complete.
Loading Bar CSS Copied.
SASS Compilation Complete
fs.js:646
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'server.key'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at Object.<anonymous> (/etc/epochtalk/websocket-server/config.js:32:13)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/etc/epochtalk/websocket-server/index.js:6:14)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
Webpack Complete.
fs.js:646
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'server.key'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at Object.<anonymous> (/etc/epochtalk/websocket-server/config.js:32:13)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/etc/epochtalk/websocket-server/index.js:6:14)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```

**Comment by Rizzrack09** [comment]
you need to be in the epochtalk folder
`cd epochtalk`
`yarn run serve`

**Comment by unenglishable** [comment]
if you're connecting locally, you can comment out the websocket security variables.

`.env`
```
# WEBSOCKET_SECURE=true
# WEBSOCKET_SERVER_KEY_NAME=server.key
# WEBSOCKET_SERVER_CERT_NAME=server.crt
```

in production we're running websocket traffic through SSL encrypted web server, so we don't use these options anyway...  will make a note of this and probably delete these options out of the `example.env` file

hope this fixes the issue for you :D

**Comment by timohzbs** [comment]
> if you're connecting locally, you can comment out the websocket security variables.
> 
> `.env`
> 
> ```
> # WEBSOCKET_SECURE=true
> # WEBSOCKET_SERVER_KEY_NAME=server.key
> # WEBSOCKET_SERVER_CERT_NAME=server.crt
> ```
> 
> in production we're running websocket traffic through SSL encrypted web server, so we don't use these options anyway... will make a note of this and probably delete these options out of the `example.env` file
> 
> hope this fixes the issue for you :D

This helped!
However I have not created a nginx config, because I have a different server handling the nginx part.
So I have the epochtalk forum on server 192.168.5.27 and my requests are handles by 192.168.5.26.
Still I have to do a config on the epochtalk server? 
The webserver is running but I cannot access it.
